vich_uploader:
    db_driver: orm

    mappings:
        participation:
            uri_prefix: /images/participation
            upload_destination: '%kernel.project_dir%/public/images/participation'

            inject_on_load: false
            delete_on_remove: false