<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPM7vrHF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPM7vrHF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPM7vrHF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPM7vrHF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPM7vrHF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PM7vrHF',
    'container.build_id' => '1d3f2372',
    'container.build_time' => 1636920063,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPM7vrHF');
